// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int nTimes = Integer.parseInt(args[0]);
		int lessThanHalf = 0;
		
		for (int i = 0; i < nTimes; i++) {
			 if (Math.random() < 0.5) {
				 lessThanHalf++;
			 }	
		}
		double ratio = ((double) lessThanHalf / (nTimes - lessThanHalf));
		System.out.println("> 0.5:  " + lessThanHalf + " times");
		System.out.println("<= 0.5: " + (nTimes - lessThanHalf) + " times");
		if (nTimes - lessThanHalf != 0) {
			System.out.println("Ratio:  " + ratio);
		}
	 }
 }